kind: pipeline
name: keynotifier
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:

- name: build
  pull: if-not-exists
  image: golang:1.16
  commands:
  - go build .

- name: sonar-scan
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/sonar-scanner:v4.3.0
